### ISSUE TITLE
Slugify thinks apostrophes are significant

### ISSUE THREAD

**Issue by BonkaBonka** [un33k/python-slugify#29] opened 2016-10-19 14:41 UTC
Given a title of "Baby's new shoes", slugify ought to return "babys-new-shoes" but instead returns "baby-s-new-shoes" which isn't right.  Seems related to changes made for #17.

**Comment by cosmicyom** [comment] 2016-10-23 11:44
I don't think it's not a bug : it's the default behavior (check the content of issue #17 and the tests in [test.py](/un33k/python-slugify/blob/master/test.py).

Maybe you lack a boolean parameter in `slugify()` to specify if a quote mark should be replaced by `'-'` or `''`.

**Comment by BonkaBonka** [comment] 2016-10-24 19:44
Yeah, my preference would indeed be to have a boolean indicating what I'd prefer to have happen.

Of course I'd prefer the boolean to default to English's stance of apostrophes being insignificant but that's probably unnecessarily provoking to non-English speakers.  :)

**Comment by un33k** [comment] 2016-10-24 20:17
I wish this was a **one size fits all** situation here, but it is not.  I am open to a **boolean** that defaults to the current behavior as I don't see a point in breaking backward compatibility.  I'll wait for a PR, or will roll it out on the next release cycle.

**Comment by un33k** [comment] 2016-11-15 22:21
Closing as per https://github.com/un33k/python-slugify/issues/30.

**Closed by un33k** 2016-11-15 22:21 UTC
